///////////////////////////////////////////////////////////
//  CollectionDescription.cs
//  Implementation of the Class CollectionDescription
//  Generated by Enterprise Architect
//  Created on:      22-May-2018 5:42:52 PM
//  Original author: Saska
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class CollectionDescription {

	private int dataset;
	private int id;
	public HistoricalCollection m_HistoricalCollection;

	public CollectionDescription(){

	}

	~CollectionDescription(){

	}

	public int Dataset{
		get{
			return dataset;
		}
		set{
			dataset = value;
		}
	}

	public int Id{
		get{
			return id;
		}
		set{
			id = value;
		}
	}

}//end CollectionDescription