///////////////////////////////////////////////////////////
//  Description.cs
//  Implementation of the Class Description
//  Generated by Enterprise Architect
//  Created on:      22-May-2018 5:42:52 PM
//  Original author: Saska
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Description {

	private int dataSet;
	private int id;
	public List<Modul1Property> m_Modul1Property;

	public Description(){

	}

	~Description(){

	}

	public int DataSet{
		get{
			return dataSet;
		}
		set{
			dataSet = value;
		}
	}

	public int Id{
		get{
			return id;
		}
		set{
			id = value;
		}
	}

}//end Description