///////////////////////////////////////////////////////////
//  IModul1.cs
//  Implementation of the Interface IModul1
//  Generated by Enterprise Architect
//  Created on:      22-May-2018 5:42:52 PM
//  Original author: Saska
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public interface IModul1  {

}//end IModul1