///////////////////////////////////////////////////////////
//  IReader.cs
//  Implementation of the Interface IReader
//  Generated by Enterprise Architect
//  Created on:      22-May-2018 5:42:52 PM
//  Original author: Saska
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public interface IReader  {

}//end IReader