///////////////////////////////////////////////////////////
//  Modul1Property.cs
//  Implementation of the Class Modul1Property
//  Generated by Enterprise Architect
//  Created on:      22-May-2018 5:42:52 PM
//  Original author: Saska
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Modul1Property {

	private Code code;
	private int modul1Value;

	public Modul1Property(){

	}

	~Modul1Property(){

	}

	public Code Code{
		get{
			return code;
		}
		set{
			code = value;
		}
	}

	public int Modul1Value{
		get{
			return Modul1Value;
		}
		set{
			Modul1Value = value;
		}
	}

}//end Modul1Property