///////////////////////////////////////////////////////////
//  Input.cs
//  Implementation of the Class Input
//  Generated by Enterprise Architect
//  Created on:      22-May-2018 5:42:52 PM
//  Original author: Saska
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using projekat;
using System.Threading;
using projekat1;

public class Input : IInput {

    public IModul1 m_Modul1 = new Modul1();
    public IModul2 m_Modul2 = new Modul2();

	public Input(){

	}

	~Input(){

	}


    // salje podatke Modulu2 koje unosi korisnik
    public bool WriteToModul2(Code code, int value)
    {
        Logger.Log("\n\nSending data from Writer directly to Historical\nData: " + code + ", " + value + "\nTime:" + DateTime.Now);
        // m_Historical.ReceiveFromWriter(code, value);

        return m_Modul2.ReceiveFromInput(code, value);
/*
        Code code;
        int value;
        int i;

        do
        {
            Console.WriteLine("Unesite redni broj Code-a:");
            Console.WriteLine("1. CODE_ANALOG");
            Console.WriteLine("2. CODE_DIGITAL");
            Console.WriteLine("3. CODE_CUSTOM");
            Console.WriteLine("4. CODE_LIMITSET");
            Console.WriteLine("5. CODE_SINGLENODE");
            Console.WriteLine("6. CODE_MULTIPLENODE");
            Console.WriteLine("7. CODE_CONSUMER");
            Console.WriteLine("8. CODE_SOURCE");
            Console.WriteLine("\n\t>>");
            i = Int32.Parse(Console.ReadLine());
        }
        while (i < 1 || i > 8);
        code = (Code)(i - 1);

        do
        {
            Console.WriteLine("Unesite vrednost za code(0-1000):");
            i = Int32.Parse(Console.ReadLine());
        } while (i < 1 || i > 1000);
        value = i;
        
        bool m = m_Modul2.ReceiveFromInput(code, value);
        Logger.Log("\n\nSlanje podataka iz Inputa direktno u Modul1\nPodatak: " + code + ", " + value + "\nVreme:" + DateTime.Now);
        
        return m;*/
    }

   
    // salje direktno podatke Modulu1 na svake 3 sekunde
    public bool WriteToModul1(Code code, int value)
    {
        Logger.Log("\n\nSending data from Writer to DumpingBuffer\nData: " + code + ", " + value + "\nTime:" + DateTime.Now);
        //m_DumpingBuffer.ReceiveFromWriter(code, value);

        return m_Modul1.ReceiveFromInput(code, value);
/*
        bool res = true;
        while ( res == true)
        {
            Random rnd = new Random();
            Code c = (Code)rnd.Next(8);
            int value = rnd.Next(1000);

            res = m_Modul1.ReceiveFromInput(c, value);
            Thread.Sleep(2000);
        }

        //return res;
        // res nikad nece vratiti true, dokle god je true nece izaci iz fje
    */}


    //Generise podatke koji ce biti poslati i poziva Input metode
    public void GenerateData()
    {
        int counter = 0;
        while (true)
        {
            Random rnd = new Random();
            Code c = (Code)rnd.Next(8);
            int value = rnd.Next(1000);

            if (counter % 5 == 0)
            {
                WriteToModul2(c, value);
            }
            else
            {
                WriteToModul1(c, value);
            }

            counter++;

            Thread.Sleep(3000);
        }
    }

}//end Input