///////////////////////////////////////////////////////////
//  Input.cs
//  Implementation of the Class Input
//  Generated by Enterprise Architect
//  Created on:      22-May-2018 5:42:52 PM
//  Original author: Saska
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using projekat1;

public class Input : IInput {

    public IModul1 m_Modul1 = new Modul1();
    public IModul2 m_Modul2 = new Modul2();

	public Input(){

	}

	~Input(){

	}


    // salje direktno podatke Modulu1 na svake 3 sekunde
    public bool WriteToModul2(Code code, int value)
    {
        Logger.Log("\n\nSlanje podataka iz Inputa direktno u Modul1\nData: " + code + ", " + value + "\nTime:" + DateTime.Now);
        // m_Historical.ReceiveFromWriter(code, value);

        //return m_Modul2.ReceiveFromWriter(code, value);

        return true;
    }

    // salje podatke Modulu2 koje unosi korisnik
    public bool ManualWriteToModul1(Code code, int value)
    {


        return false;
    }

}//end Input