///////////////////////////////////////////////////////////
//  Modul2.cs
//  Implementation of the Class Modul2
//  Generated by Enterprise Architect
//  Created on:      22-May-2018 5:42:52 PM
//  Original author: Saska
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Modul2 : IModul2 {

	public CollectionDescription m_CollectionDescription;

	public Modul2(){

	}

	~Modul2(){

	}

    

    
}//end Modul2