///////////////////////////////////////////////////////////
//  Modul1.cs
//  Implementation of the Class Modul1
//  Generated by Enterprise Architect
//  Created on:      22-May-2018 5:42:52 PM
//  Original author: Saska
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Modul1 : IModul1 {

	public Modul2 m_Modul2;
	public ListDescription m_ListDescription;

	public Modul1(){

	}

	~Modul1(){

	}

}//end Modul1