///////////////////////////////////////////////////////////
//  Modul2Property.cs
//  Implementation of the Class Modul2Property
//  Generated by Enterprise Architect
//  Created on:      22-May-2018 5:42:52 PM
//  Original author: Saska
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Modul2Property {

    private Code code;
    private int historicalValue;

    public Modul2Property()
    {

    }


    public Code Code
    {
        get
        {
            return code;
        }
        set
        {
            code = value;
        }
    }

    public int HistoricalValue
    {
        get
        {
            return historicalValue;
        }
        set
        {
            historicalValue = value;
        }
    }

}//end Modul2Property