///////////////////////////////////////////////////////////
//  Reader.cs
//  Implementation of the Class Reader
//  Generated by Enterprise Architect
//  Created on:      22-May-2018 5:42:52 PM
//  Original author: Saska
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;


public class Reader : IReader {

	public IModul2 m_Modul2;

	public Reader(){

	}

	~Reader(){

	}
    public bool ReadDataFromModul2(Code code, DateTime start, DateTime end)
    {
        m_Modul2 = new Modul2();
        List<CollectionDescription> returnList = new List<CollectionDescription>();

        returnList = m_Modul2.ReadDataForReader(code);
            if (returnList.Count != 0)
            {
                Console.WriteLine("------------------------------------------------");
                Console.WriteLine("-------Element list for {0} code: -----", code);
                Console.WriteLine("------------------------------------------------");

                foreach (CollectionDescription item in returnList)
                {
                    if (item.timeStamp >= start && item.timeStamp <= end)
                    {
                        Console.WriteLine(item);
                        Console.WriteLine("***********************************");
                    }
                Console.WriteLine("------------------------------------------------");
                }
            }
            else
            {
                Console.WriteLine("Fajl za {0} code je prazan...");
            }
            return true;
        }
   
}//end Reader