///////////////////////////////////////////////////////////
//  Reader.cs
//  Implementation of the Class Reader
//  Generated by Enterprise Architect
//  Created on:      22-May-2018 5:42:52 PM
//  Original author: Saska
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Reader : IReader {

	public Modul2 m_Modul2;

	public Reader(){

	}

	~Reader(){

	}

}//end Reader