///////////////////////////////////////////////////////////
//  CollectionDescription.cs
//  Implementation of the Class CollectionDescription
//  Generated by Enterprise Architect
//  Created on:      22-May-2018 5:42:52 PM
//  Original author: Saska
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class CollectionDescription {

	private int dataset;
	private int id;
    public HistoricalCollection m_HistoricalCollection = new HistoricalCollection(); // HistoricalCollection - niz modul2propertyja
    public DateTime timeStamp;

    public CollectionDescription(){

	}

	~CollectionDescription(){

	}

	public int Dataset{
		get{ return dataset; }
		set{ dataset = value; }
	}

	public int Id{
		get{ return id; }
		set{ id = value; }
	}

    public override string ToString()
    {
        return "ID: " + Id + ", DataSet: " + Dataset + ", Code: " + m_HistoricalCollection.m_Modul2Property[0].Code + "\nVrednost: " + m_HistoricalCollection.m_Modul2Property[0].Modul2Value +"\n TimeStamp: " + timeStamp + "\n";
        }

}//end CollectionDescription