///////////////////////////////////////////////////////////
//  HistoricalCollection.cs
//  Implementation of the Class HistoricalCollection
//  Generated by Enterprise Architect
//  Created on:      22-May-2018 5:42:52 PM
//  Original author: Saska
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class HistoricalCollection {

	public Modul2Property[] m_Modul2Property = new Modul2Property[1]; // niz modul2propertija

	public HistoricalCollection(){

	}

	~HistoricalCollection(){

	}

}//end HistoricalCollection