///////////////////////////////////////////////////////////
//  ListDescription.cs
//  Implementation of the Class ListDescription
//  Generated by Enterprise Architect
//  Created on:      22-May-2018 5:42:52 PM
//  Original author: Saska
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using projekat;



public class ListDescription {

    public List<Description> m_Description = new List<Description>();


    public ListDescription(){

	}

	~ListDescription(){

	}

}//end ListDescription