///////////////////////////////////////////////////////////
//  Modul1Property.cs
//  Implementation of the Class Modul1Property
//  Generated by Enterprise Architect
//  Created on:      22-May-2018 5:42:52 PM
//  Original author: Saska
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Modul1Property
{
    private Code _code;
    private int _value;

    public Modul1Property()
    {

    }

    public Modul1Property(Code code, int value)
    {
        if (value == null)
        {
            throw new ArgumentNullException("Value is null");
        }
        if (code == null)
        {
            throw new ArgumentNullException("Value is null");
        }
        _code = code;
        _value = value;

    }

    public Code Code
    {
        get
        {
            return _code;
        }
        set
        {
            _code = value;
        }
    }

    public int Value
    {
        get
        {
            return _value;
        }
        set
        {
            _value = value;
        }
    }

    public override string ToString()
    {
        return "Code: " + _code + "\tValue: " + _value;
    }
}